# Generated by Django 4.0.4 on 2022-06-28 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('snable_saas', '0025_careerapplications'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact_training_hiring_form',
            name='course_name',
            field=models.CharField(default=None, max_length=150),
        ),
    ]
