# Generated by Django 4.0.4 on 2022-06-28 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('snable_saas', '0026_contact_training_hiring_form_course_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentDownloadBroucher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=100)),
                ('mobile_number', models.BigIntegerField()),
                ('email', models.CharField(max_length=50)),
                ('qualification', models.CharField(max_length=50)),
                ('address', models.CharField(max_length=250)),
                ('course_name', models.CharField(default=None, max_length=150)),
            ],
        ),
    ]
