# Generated by Django 4.0.4 on 2022-07-15 10:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('snable_saas', '0027_studentdownloadbroucher'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='slug',
        ),
    ]
