# Generated by Django 4.0.4 on 2022-07-15 10:45

import autoslug.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('snable_saas', '0028_remove_post_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='new_slug',
            field=autoslug.fields.AutoSlugField(default=None, editable=False, null=True, populate_from='title', unique=True),
        ),
    ]
